import { IconBrandNetflix } from "@tabler/icons-react";
import {
  Zap,
  Compass,
  Palette,
  Laugh,
  Shield,
  FileText,
  Drama,
  Users,
  Wand2,
  Clock,
  Skull,
  Music,
  HelpCircle,
  Heart,
  Rocket,
  Tv,
  GhostIcon as Thriller,
  Swords,
  Mountain,
  BookOpenCheck,
  Mic,
  Globe,
  MonitorPlay,
  Landmark,
  CloudMoon,
} from "lucide-react";

export const movieGenres = [
  {
    name: "Action",
    id: 28,
    icon: Zap,
    description: "High-energy films with intense sequences",
    color: "text-red-700 border-red-950",
    iconColor: "text-red-600",
  },
  {
    name: "Adventure",
    id: 12,
    icon: Compass,
    description: "Exciting journeys and exploration",
    color: "text-orange-700 border-orange-950",
    iconColor: "text-orange-600",
  },
  {
    name: "Animation",
    id: 16,
    icon: Palette,
    description: "Animated films for all ages",
    color: "text-purple-700 border-purple-950",
    iconColor: "text-purple-600",
  },
  {
    name: "Comedy",
    id: 35,
    icon: Laugh,
    description: "Funny and entertaining movies",
    color: "text-yellow-700 border-yellow-950",
    iconColor: "text-yellow-600",
  },
  {
    name: "Crime",
    id: 80,
    icon: Shield,
    description: "Criminal activities and investigations",
    color: "text-gray-700 border-gray-950",
    iconColor: "text-gray-600",
  },
  {
    name: "Documentary",
    id: 99,
    icon: FileText,
    description: "Real-life stories and facts",
    color: "text-blue-700 border-blue-950",
    iconColor: "text-blue-600",
  },
  {
    name: "Drama",
    id: 18,
    icon: Drama,
    description: "Emotional and character-driven stories",
    color: "text-indigo-700 border-indigo-950",
    iconColor: "text-indigo-600",
  },
  {
    name: "Family",
    id: 10751,
    icon: Users,
    description: "Perfect for family movie nights",
    color: "text-green-700 border-green-950",
    iconColor: "text-green-600",
  },
  {
    name: "Fantasy",
    id: 14,
    icon: Wand2,
    description: "Magical worlds and creatures",
    color: "text-violet-700 border-violet-950",
    iconColor: "text-violet-600",
  },
  {
    name: "History",
    id: 36,
    icon: Clock,
    description: "Stories from the past",
    color: "text-amber-700 border-amber-950",
    iconColor: "text-amber-600",
  },
  {
    name: "Horror",
    id: 27,
    icon: Skull,
    description: "Scary and suspenseful films",
    color: "text-red-700 border-red-950",
    iconColor: "text-red-600",
  },
  {
    name: "Music",
    id: 10402,
    icon: Music,
    description: "Musical performances and stories",
    color: "text-pink-700 border-pink-950",
    iconColor: "text-pink-600",
  },
  {
    name: "Mystery",
    id: 9648,
    icon: HelpCircle,
    description: "Puzzles and unsolved cases",
    color: "text-slate-700 border-slate-950",
    iconColor: "text-slate-600",
  },
  {
    name: "Romance",
    id: 10749,
    icon: Heart,
    description: "Love stories and relationships",
    color: "text-rose-700 border-rose-950",
    iconColor: "text-rose-600",
  },
  {
    name: "Science Fiction",
    id: 878,
    icon: Rocket,
    description: "Futuristic and sci-fi themes",
    color: "text-cyan-700 border-cyan-950",
    iconColor: "text-cyan-600",
  },
  {
    name: "TV Movie",
    id: 10770,
    icon: Tv,
    description: "Made-for-television films",
    color: "text-teal-700 border-teal-950",
    iconColor: "text-teal-600",
  },
  {
    name: "Thriller",
    id: 53,
    icon: Thriller,
    description: "Suspenseful and edge-of-seat films",
    color: "text-red-700 border-red-950",
    iconColor: "text-red-600",
  },
  {
    name: "War",
    id: 10752,
    icon: Swords,
    description: "Military conflicts and battles",
    color: "text-stone-700 border-stone-950",
    iconColor: "text-stone-600",
  },
  {
    name: "Western",
    id: 37,
    icon: Mountain,
    description: "Wild west and frontier stories",
    color: "text-orange-700 border-orange-950",
    iconColor: "text-orange-600",
  },
];
export const tvGenres = [
  {
    name: "Action & Adventure",
    id: 10759,
    icon: Zap,
    description: "Thrilling TV with action and exploration",
    color: "text-red-700 border-red-950",
    iconColor: "text-red-600",
  },
  {
    name: "Animation",
    id: 16,
    icon: Palette,
    description: "Animated shows for all ages",
    color: "text-purple-700 border-purple-950",
    iconColor: "text-purple-600",
  },
  {
    name: "Comedy",
    id: 35,
    icon: Laugh,
    description: "TV that makes you laugh",
    color: "text-yellow-700 border-yellow-950",
    iconColor: "text-yellow-600",
  },
  {
    name: "Crime",
    id: 80,
    icon: Shield,
    description: "Crime investigations and dramas",
    color: "text-gray-700 border-gray-950",
    iconColor: "text-gray-600",
  },
  {
    name: "Documentary",
    id: 99,
    icon: FileText,
    description: "True stories and real-world topics",
    color: "text-blue-700 border-blue-950",
    iconColor: "text-blue-600",
  },
  {
    name: "Drama",
    id: 18,
    icon: BookOpenCheck,
    description: "Emotional, character-driven stories",
    color: "text-indigo-700 border-indigo-950",
    iconColor: "text-indigo-600",
  },
  {
    name: "Family",
    id: 10751,
    icon: Users,
    description: "TV shows suitable for all ages",
    color: "text-green-700 border-green-950",
    iconColor: "text-green-600",
  },
  {
    name: "Kids",
    id: 10762,
    icon: Tv,
    description: "Fun and friendly content for kids",
    color: "text-teal-700 border-teal-950",
    iconColor: "text-teal-600",
  },
  {
    name: "Mystery",
    id: 9648,
    icon: HelpCircle,
    description: "Puzzling and intriguing stories",
    color: "text-slate-700 border-slate-950",
    iconColor: "text-slate-600",
  },
  {
    name: "News",
    id: 10763,
    icon: Mic,
    description: "Latest happenings and headlines",
    color: "text-cyan-700 border-cyan-950",
    iconColor: "text-cyan-600",
  },
  {
    name: "Reality",
    id: 10764,
    icon: MonitorPlay,
    description: "Real-life experiences and drama",
    color: "text-orange-700 border-orange-950",
    iconColor: "text-orange-600",
  },
  {
    name: "Sci-Fi & Fantasy",
    id: 10765,
    icon: Rocket,
    description: "Futuristic and magical adventures",
    color: "text-pink-700 border-pink-950",
    iconColor: "text-pink-600",
  },
  {
    name: "Soap",
    id: 10766,
    icon: Heart,
    description: "Emotional and romantic TV dramas",
    color: "text-rose-700 border-rose-950",
    iconColor: "text-rose-600",
  },
  {
    name: "Talk",
    id: 10767,
    icon: Mic,
    description: "Discussion-based shows and interviews",
    color: "text-lime-700 border-lime-950",
    iconColor: "text-lime-600",
  },
  {
    name: "War & Politics",
    id: 10768,
    icon: Landmark,
    description: "Conflicts, diplomacy, and leadership",
    color: "text-stone-700 border-stone-950",
    iconColor: "text-stone-600",
  },
  {
    name: "Western",
    id: 37,
    icon: Mountain,
    description: "Wild west TV stories",
    color: "text-orange-700 border-orange-950",
    iconColor: "text-orange-600",
  },
];

export const productionCompanies = [
  {
    name: "Marvel Studios",
    id: 420,
    icon: Shield,
    description: "Superhero and action films",
  },
  {
    name: "Warner Bros.",
    id: 174,
    icon: Drama,
    description: "Major Hollywood studio",
  },
  {
    name: "Universal Pictures",
    id: 33,
    icon: Rocket,
    description: "Global entertainment company",
  },
  {
    name: "Disney",
    id: 2,
    icon: Wand2,
    description: "Family and animated films",
  },
  {
    name: "Sony Pictures",
    id: 5,
    icon: Tv,
    description: "Entertainment and media",
  },
  {
    name: "Paramount Pictures",
    id: 4,
    icon: Mountain,
    description: "Classic Hollywood studio",
  },
  {
    name: "20th Century Studios",
    id: 25,
    icon: Clock,
    description: "Major film studio",
  },
  {
    name: "Netflix",
    id: 178464,
    icon: IconBrandNetflix,
    description: "Streaming platform originals",
  },
  {
    name: "A24",
    id: 41077,
    icon: Palette,
    description: "Independent film company",
  },
  {
    name: "Blumhouse Productions",
    id: 3172,
    icon: Skull,
    description: "Horror and thriller films",
  },
  {
    name: "Pixar",
    id: 3,
    icon: Palette,
    description: "Computer animation studio",
  },
  {
    name: "Lucasfilm",
    id: 1,
    icon: Rocket,
    description: "Star Wars and adventure films",
  },
];
export const tvNetworks = [
  {
    name: "Netflix",
    id: 213,
    icon: Tv,
    description: "Global streaming platform with original series",
  },
  {
    name: "HBO",
    id: 49,
    icon: Drama,
    description: "High-quality premium television network",
  },
  {
    name: "Amazon Prime Video",
    id: 1024,
    icon: Rocket,
    description: "Streaming service with original content",
  },
  {
    name: "Hulu",
    id: 453,
    icon: Wand2,
    description: "Popular US-based streaming network",
  },
  {
    name: "Disney+",
    id: 2739,
    icon: Palette,
    description: "Streaming home of Disney, Marvel & Star Wars",
  },
  {
    name: "Apple TV+",
    id: 2552,
    icon: Tv,
    description: "Apple’s premium original content platform",
  },
  {
    name: "The CW",
    id: 71,
    icon: Heart,
    description: "Teen and fantasy-oriented TV shows",
  },
  {
    name: "BBC One",
    id: 4,
    icon: Mic,
    description: "UK broadcaster with acclaimed dramas",
  },
  {
    name: "NBC",
    id: 6,
    icon: Globe,
    description: "Major US network with long-running series",
  },
  {
    name: "CBS",
    id: 16,
    icon: Landmark,
    description: "Network known for crime, procedural, and sitcoms",
  },
  {
    name: "Paramount+",
    id: 4330,
    icon: Mountain,
    description: "Home of Star Trek and other franchises",
  },
];

export const keywordTopics = [
  { label: "Horror", value: "315058" },
  { label: "Survival", value: "10349" },
  { label: "South Korea", value: "261681" },
  { label: "Zombie", value: "12377" },
  { label: "Teen Drama", value: "155722" },
  { label: "Teen Drama 2", value: "6270" },

  { label: "Artificial Intelligence", value: "310" },
  { label: "Vampire", value: "3133" },
  { label: "Future", value: "2964" },
  { label: "Based on Novel/Book", value: "818" },
  { label: "Anime", value: "210024" },
  { label: "Ghost", value: "9839" },
  { label: "War", value: "1956" },
  { label: "Disaster", value: "189411" },
  { label: "Time-loop", value: "10854" },
  { label: "Sequel", value: "9663" },
  { label: "Action-Comedy", value: "247799" },
  { label: "18+", value: "267122" },
  { label: "Horrified", value: "325825", icon: CloudMoon },
];

export const tmdbRegions = [
  { value: "US", label: "United States" },
  { value: "GB", label: "United Kingdom" },
  { value: "CA", label: "Canada" },
  { value: "AU", label: "Australia" },
  { value: "IN", label: "India" },
  { value: "KR", label: "South Korea" },
  { value: "JP", label: "Japan" },
  { value: "FR", label: "France" },
  { value: "DE", label: "Germany" },
  { value: "IT", label: "Italy" },
  { value: "ES", label: "Spain" },
  { value: "CN", label: "China" },
  { value: "RU", label: "Russia" },
  { value: "BR", label: "Brazil" },
  { value: "MX", label: "Mexico" },
  { value: "TH", label: "Thailand" },
  { value: "ID", label: "Indonesia" },
  { value: "VN", label: "Vietnam" },
  { value: "NG", label: "Nigeria" },
  { value: "AR", label: "Argentina" },
  { value: "TR", label: "Turkey" },
  { value: "ZA", label: "South Africa" },
];
