export interface ReusableSwiperTypes {
  id: string; // slug used for routing + lookup
  endpoint: string;
  media_type: string;
  params: Record<string, string | number>;
  label?: string; // optional UI badge (year, etc.)
  displayName: string; // purely for UI text
  isVisible?: boolean;
  type: string;
}
export const movie_endpoints: ReusableSwiperTypes[] = [
  {
    id: "popular-movie",
    displayName: "Popular Movies",
    endpoint: "discover",
    media_type: "movie",
    type: "movie",
    params: { sort_by: "popularity.desc" },
  },
  {
    id: "christmas-santa-movie",
    displayName: "Christmas / Santa Movies",
    endpoint: "discover",
    media_type: "movie",
    type: "movie",
    params: { with_keywords: 1991, sort_by: "popularity.desc" },
  },
  {
    id: "zombie-movies",
    displayName: "Zombie Movies",
    endpoint: "discover",
    media_type: "movie",
    type: "movie",
    params: { with_keywords: 186565, sort_by: "popularity.desc" },
  },
  {
    id: "found-footage",
    displayName: "Found Footage Horror",
    endpoint: "discover",
    media_type: "movie",
    type: "movie",
    params: { with_keywords: 163053, sort_by: "popularity.desc" },
  },
  {
    id: "psychological-thriller",
    displayName: "Psychological Thrillers",
    endpoint: "discover",
    media_type: "movie",
    type: "movie",
    params: { with_keywords: 12565, sort_by: "popularity.desc" },
  },
  {
    id: "slasher-horror",
    displayName: "Slasher Horror",
    endpoint: "discover",
    media_type: "movie",
    type: "movie",
    params: { with_keywords: 12339, sort_by: "popularity.desc" },
  },
  {
    id: "time-loop-movies",
    displayName: "Time-Loop Movies",
    endpoint: "discover",
    media_type: "movie",
    type: "movie",
    params: { with_keywords: 10854, sort_by: "popularity.desc" },
  },

  {
    id: "alien-invasion",
    displayName: "Alien Invasion",
    endpoint: "discover",
    media_type: "movie",
    type: "movie",
    params: { with_keywords: 9951, sort_by: "popularity.desc" },
  },
  {
    id: "time-travel",
    displayName: "Time Travel Movies",
    endpoint: "discover",
    media_type: "movie",
    type: "movie",
    params: { with_keywords: 4379, sort_by: "popularity.desc" },
  },
  {
    id: "true-story",
    displayName: "Based on True Story",
    endpoint: "discover",
    media_type: "movie",
    type: "movie",
    params: { with_keywords: 9672, sort_by: "popularity.desc" },
  },
];

export const tv_endpoints: ReusableSwiperTypes[] = [
  {
    id: "popular-tv",
    displayName: "Popular TV Shows",
    endpoint: "discover",
    media_type: "tv",
    type: "tv-show",
    params: { sort_by: "popularity.desc" },
  },
  {
    id: "zombie-tv",
    displayName: "Zombie TV Shows",
    endpoint: "discover",
    media_type: "tv",
    type: "tv-show",
    params: { with_keywords: 186565, sort_by: "popularity.desc" },
  },
  {
    id: "crime-docuseries",
    displayName: "Crime Docuseries",
    endpoint: "discover",
    media_type: "tv",
    type: "tv-show",
    params: { with_genres: 99, sort_by: "popularity.desc" },
  },
  {
    id: "mystery-series",
    displayName: "Mystery Series",
    endpoint: "discover",
    media_type: "tv",
    type: "tv-show",
    params: { with_genres: 9648, sort_by: "popularity.desc" },
  },
  {
    id: "sci-fi-series",
    displayName: "Sci-Fi Series",
    endpoint: "discover",
    media_type: "tv",
    type: "tv-show",
    params: { with_genres: 10765, sort_by: "popularity.desc" },
  },
  {
    id: "teen-drama",
    displayName: "Teen Drama",
    endpoint: "discover",
    media_type: "tv",
    type: "tv-show",
    params: { with_keywords: 6270, sort_by: "popularity.desc" },
  },
  {
    id: "survival-tv",
    displayName: "Survival Shows",
    endpoint: "discover",
    media_type: "tv",
    type: "tv-show",
    params: { with_keywords: 9826, sort_by: "popularity.desc" },
  },
  {
    id: "medical-drama",
    displayName: "Medical Drama",
    endpoint: "discover",
    media_type: "tv",
    type: "tv-show",
    params: { with_keywords: 12361, sort_by: "popularity.desc" },
  },
  {
    id: "political-drama",
    displayName: "Political Drama",
    endpoint: "discover",
    media_type: "tv",
    type: "tv-show",
    params: { with_keywords: 9994, sort_by: "popularity.desc" },
  },
  {
    id: "sitcoms",
    displayName: "Sitcoms",
    endpoint: "discover",
    media_type: "tv",
    type: "tv-show",
    params: { with_genres: 35, sort_by: "popularity.desc" },
  },
];
export const anime_endpoints: ReusableSwiperTypes[] = [
  {
    id: "anime-movies",
    displayName: "Anime Movies",
    endpoint: "discover",
    media_type: "movie",
    type: "anime",
    params: { with_keywords: 210024, sort_by: "popularity.desc" },
  },
  {
    id: "anime-series",
    displayName: "Anime Series",
    endpoint: "discover",
    media_type: "tv",
    type: "anime",
    params: { with_keywords: 210024, sort_by: "popularity.desc" },
  },
  {
    id: "isekai",
    displayName: "Isekai Anime",
    endpoint: "discover",
    media_type: "tv",
    type: "anime",
    params: { with_keywords: 287501, sort_by: "popularity.desc" },
  },
  {
    id: "shonen",
    displayName: "Shōnen Anime",
    endpoint: "discover",
    media_type: "tv",
    type: "anime",
    params: { with_keywords: 287502, sort_by: "popularity.desc" },
  },
  {
    id: "dark-anime",
    displayName: "Dark Anime",
    endpoint: "discover",
    media_type: "tv",
    type: "anime",
    params: { with_keywords: 9715, sort_by: "popularity.desc" },
  },
  {
    id: "mecha",
    displayName: "Mecha Anime",
    endpoint: "discover",
    media_type: "tv",
    type: "anime",
    params: { with_keywords: 4565, sort_by: "popularity.desc" },
  },
  {
    id: "sports-anime",
    displayName: "Sports Anime",
    endpoint: "discover",
    media_type: "tv",
    type: "anime",
    params: { with_keywords: 180547, sort_by: "popularity.desc" },
  },
  {
    id: "romance-anime",
    displayName: "Romance Anime",
    endpoint: "discover",
    media_type: "tv",
    type: "anime",
    params: { with_genres: 10749, sort_by: "popularity.desc" },
  },
  {
    id: "fantasy-anime",
    displayName: "Fantasy Anime",
    endpoint: "discover",
    media_type: "tv",
    type: "anime",
    params: { with_genres: 14, sort_by: "popularity.desc" },
  },
  {
    id: "psychological-anime",
    displayName: "Psychological Anime",
    endpoint: "discover",
    media_type: "tv",
    type: "anime",
    params: { with_keywords: 156212, sort_by: "popularity.desc" },
  },
];
